name: Release
on:
  create:
    tags:
      - v*
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release
